Fix 2.6.x failing to compile on gcc 13.1.1 because of missing headers
I was getting this error until I added this header:
/home/dogunbound/SFML/SFML/src/SFML/Audio/SoundFileReaderMp3.cpp:68:23:
error: ‘uint64_t’ is not a member of ‘std’;

This is a fix